### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by thnx-cul8ter** [UlisseMini/luamc#5]
hey so i just wanted to try the mod since it looks cool and got this
https://pastebin.com/y4thDajW
idk wth this means but its not good
sorry to bother you

**Comment by goopsie** [comment]
Sorry for getting to this so late, do you have the [luaj .jar file](https://github.com/UlisseMini/luamc/blob/master/libs/luaj-jse-3.0.1.jar) in your mods folder as well?

**Comment by thnx-cul8ter** [comment]
i dont have the pack i was using anymore so idk

**Comment by thnx-cul8ter** [comment]
im just gonna close this
